### PR TITLE
Small cleanups and a few SURVEY questions

### PR DESCRIPTION
**Pull request by jdmgoogle**
Small changes, including
- Making InfoUri an optional field in BallotMeasure (see #155);
- Making ExternalIdentifier an unbounded repeating element;
- Making values in ExternalIdentifiers required;
- Removing 'retention' as a type for BallotMeasureContest (there's a RetentionContest type for that, see #160);
- Making VotesAllowed optional; and
- Adding two SURVEY questions.

### CODE REVIEW

**Comment by jungshadow** [comment]
LGTM

**Comment by jungshadow** [comment]
Oh, to answer the survey, yes, we do need to keep the prefix and suffix because Wisconsin:

    W399S7248 County Road Z, Eagle WI 53119

**Comment by jdmgoogle** [comment]
But how does that work with the (required) StartHouseNumber and EndHouseNumber elements in the parent element?

**Comment by jdmgoogle** [comment]
I just checked and it looks like we (Google) don't use the prefix and suffix in our pipeline, so these fields have never been used as far as I can tell. @jktomer may know more, but it looks like we can remove some more unused fields.

Also I moved isWriteIn to be an element instead of an attribute since it was the only non-identifier, non-actual-XML-attribute (i.e., language) to be an attribute instead of an element. I suspect that it was a 1622.2 conversion issue on my part.

**Comment by jungshadow** [comment]
Never mind, I just realized that we now have UnitNumber, which I think solves this problem. I believe we dealt with these addresses as one-offs (i.e. the numbers didn't fluctuate and start==end). I'd have @pkoms or @nomadaisy weigh in on this as they're more familiar with the current dataset.

Just a note on this, I don't feel the survey discussion holds up the merge, but I would be happy if the surveys moved to their own "Up for Discussion" issue, since I'm not sure how if this PR comment thread is going to be easily found by posterity :) Plus, seems a bit weird to have a future PR request reference another PR request as the basis for a fix (unless a bug was introduced). I don't mind creating the issue, if you need me to.

**Comment by jdmgoogle** [comment]
Filed issue #162 to document the `NonHouseAddress` cleanup. The other cleanups not covered by issues here (Making ExternalIdentifier an unbounded repeating element; Making values in ExternalIdentifiers required; and Making VotesAllowed optional) are trivial fixes to the way things should have been in the first place.

**Comment by jungshadow** [comment]
Sounds good and thanks for filing #162. You still get a "LGTM" from me on this.

**Comment by jungshadow** [comment]
@jdmgoogle If you don't hear anything from @nomadaisy and @pkoms by Monday EOD and you get another LGTM per the contributing process, feel free to merge away.

**Comment by jktomer** [comment]
House number prefix and suffix are a bit of a tricky case. @jdmgoogle is right that we presently ignore them (because our own geo stack doesn't seem to support them), but the standard shouldn't be limited to only the things Google Maps recognizes today.

If there is a useful case to be made for either adding a house number prefix/suffix (open question: how would that interact with nonempty ranges? Presumably the same prefix and suffix gets added to each of them; is that useful in reality? Also note that W399S7248 doesn't have an obvious useful prefix+house number+suffix representation.) or an alternate HouseDesignator string to replace start+end house number (no ranges allowed for non-integral house number).

Regardless, breaking fields out into non-house-address seems pointless; I'm not sure why that's even still a thing, given that DetailAddressType exists nowhere else, so there's no common element to factor out. Anything we care about could live directly in StreetSegment IMO. (I don't insist; what we have is fine.)

Does anyone have a count of addresses covered by existing or past feeds which can't use an integer house number? (If you also have a list, I can see how many of them we can geocode as-is, but again, we shouldn't limit ourselves to being able to represent only data that Google can geocode, since there are many other potential users of this data, and Google's capabilities will change over time too.)

**Comment by jdmgoogle** [comment]
@jktomer It's not just what Google can or can't do right now, and you kind of touched on this in your response:

> (no ranges allowed for non-integral house number)

Right now we primarily use street segments to perform range-based lookups of addresses. Having prefix and suffix elements (beyond the `Unit` element) will limit how we do ranges. E.g., if the range is [1A, 3A], does that mean the addresses are {1A, 2A, 3A}, or is the range {1A, 1B, 1C, ..., 2ZX, 2ZY, 2ZZ, 3A}?

If we do want to represent complicated addresses in 5.0 (as opposed to folding it in to #118 in 5.1) then my only suggestion is to add a `StartHouseNumberPrefix` and `StartHouseNumberSuffix`, and if either of those are present then we ignore `EndHouseNumber`.

**Comment by jktomer** [comment]
Yeah, I think that, like the presence of unit numbers, non-integer house numbers should restrict a segment to single-address only (not entirely rare, as it happens, but obnoxious).

Regardless, this can definitely wait until 5.1 from our perspective.

**Comment by jdmgoogle** [comment]
Pinging @jktomer @cjerdonek @pstenbjorn for review/LGTM.

**Comment by pstenbjorn** [comment]
@jdmgoogle and @jktomer the original commits in this PR LGTM.  I also agree that restructuring additional street segment elements might be better left to 5.1.

**Comment by jdmgoogle** [comment]
Thanks. Merging.

**Comment by jdmgoogle** [comment]
I filed #166 as a reminder to better handle complex and non-numeric addresses in the `StreetSegment` element in 5.1

**Pull request merged**
