### PR TITLE
Strike authors in Sphinx config

### LINKED ISSUE #227: Strike authors from Sphinx config file until there's a complete list
There's an abbreviated list of authors in `conf.py` that should be removed until we have a complete list of contributors. Additionally, the list currently break the PDF rendering.

### PR DESCRIPTION
**Pull request by jungshadow**
Closes #227

### CODE REVIEW

**Comment by jungshadow** [comment]
Can I get a quick LGTM on this from some folks? Right now, the [ReadTheDocs PDF](https://media.readthedocs.org/pdf/vip-specification/vip5/vip-specification.pdf) renders pretty weird. Clearly the tables need to be addressed at some point too, but...it's hard to account for print. /cc @pstenbjorn @jdmgoogle @jktomer @pkoms @nomadaisy @MariaDemocracyWorks @cjerdonek

**Comment by nomadaisy** [comment]
LGTM

**Comment by pstenbjorn** [comment]
LGTM

**Comment by jdmgoogle** [comment]
LGTM

**Pull request merged**
