### PR TITLE
Created first pass at 5.1 release notes.

### PR DESCRIPTION
**Pull request by jdmgoogle**
Addresses #281 

See $SUBJECT

### CODE REVIEW

**Comment by pstenbjorn** [comment]
@jdmgoogle LGTM is there more coming to this commit?

**Comment by jdmgoogle** [comment]
@pstenbjorn Not this one, no. As a few more changes go into the release I'll update the release notes more, but this is just getting the ball rolling.

**Comment by jdmgoogle** [comment]
Paging @cjerdonek @nomadaisy @MariaBianchi etc :)

**Comment by cjerdonek** [comment]
+1

**Pull request merged**
