### PR TITLE
Remove NonHouseAddress and fold its elements into the parent StreetSegment

### PR DESCRIPTION
**Pull request by jdmgoogle**
See $SUBJECT.

This involved much adjusting of the RST tables.

### CODE REVIEW

**Comment by jdmgoogle** [comment]
This addresses issue #258.

**Comment by jungshadow** [comment]
LGTM (appropriate gif btw)

**Comment by jdmgoogle** [comment]
Ping @jktomer @pstenbjorn @cjerdonek @jen-tolentino @nomadaisy.

**Comment by nomadaisy** [comment]
LGTM

**Pull request merged**
