### PR TITLE
Precinct simplification

### PR DESCRIPTION
**Pull request by pstenbjorn**
@jdmgoogle @jdmgoogle please review removed split, consolidated precinct usage.  @demcg cleaned up some spacing issues as well

### CODE REVIEW

**Comment by pstenbjorn** [comment]
Did anyone have comments about this commit? If not what are folks thoughts on merging it?

**Comment by jungshadow** [comment]
@pstenbjorn This is related to (and hopefully closes) #27, right? If I understand correctly, the presence of `Precinct.PrecinctSplitName` denotes that it's a precinct split. If that's correct, it looks good to me.

**Comment by pstenbjorn** [comment]
@jungshadow Yes this should close #27 and yes, the `PrecinctSplitName` element would be used as a designation that this was part of a larger precinct.  I have some XML examples of this.

**Comment by cjerdonek** [comment]
@pstenbjorn Do you have a preference as to which PR should be merged first, yours or mine?  I was going to go ahead, but I could wait.

**Comment by pstenbjorn** [comment]
@cjerdonek I don't have a specific preference as they do not affect the same elements.  This one has fewer changes but has had less discussion.  I would be interested in hearing from @pkoms or @nomadaisy  on this.

**Comment by cjerdonek** [comment]
@pstenbjorn Okay, thanks, then I will go ahead on mine.

**Comment by nomadaisy** [comment]
I think this consolidation looks good. This would not only simplify things, but require that all precinct splits and precincts be represented together, which sometimes causes polling location associations to be overlooked in places that associate locations differently in various parts of the state.

**Comment by jdmgoogle** [comment]
This PR looks good to me. Thanks, @pstenbjorn.

**Comment by pstenbjorn** [comment]
Thank you Noma and Justin I merged the PR and deleted the branch.

**Pull request merged**
