### PR TITLE
FINAL sync to NIST and documentation clean-ups

### PR DESCRIPTION
**Pull request by jdmgoogle**
This is the *final* cleanup for 5.1.

It involves the following changes, almost entirely to sync with NIST:

1. Move `SequenceOrder` from `Candidate` to `BallotSelectionBase` (NIST change);
2. Update `CandidateContest` to support multiple `PrimaryPartyIds` (NIST change);
3. Add `Gender` to `Person` (NIST change);
4. Make `TermType` in `Term` optional (NIST change); and
5. Add "borough" to `DistrictType` (NIST change).

The sample feed and element examples have been updated, too.

### CODE REVIEW

**Comment by jdmgoogle** [comment]
Ping @pstenbjorn @nomadaisy @cjerdonek @MariaBianchi

**Comment by jdmgoogle** [comment]
For the sake of actually getting this released, I'm going to merge in this PR and cut the official 5.1 release today  at 4pm (post VIP call) unless there are any objections before then.

**Comment by pstenbjorn** [comment]
Thank you @jdmgoogle LGTM

**Comment by jktomer** [comment]
LGTM

**Pull request merged**
