### PR TITLE
Documentation for Office

### LINKED ISSUE #199: Document Office element
Document the `Office` element.

### PR DESCRIPTION
**Pull request by jungshadow**
Closes #199

### CODE REVIEW

**Comment by jdmgoogle** [comment]
LGTM. Could you add in an example block from the sample feed?

**Comment by pstenbjorn** [comment]
LGTM

**Comment by jungshadow** [comment]
@jdmgoogle Just to be sure, how does [this sample](https://github.com/votinginfoproject/vip-specification/pull/209/files#diff-0aca2cdf898ae38c81766b2ba6abed61L46) look? Once you give the go-ahead, I'll merge.

**Comment by jdmgoogle** [comment]
In that link I can see the line/diff, but when I try to view the page, I don't see it. E.g.,

https://github.com/votinginfoproject/vip-specification/blob/feature/199-document-office/docs/xml/elements/office.rst

**Comment by jungshadow** [comment]
Ah...I don't think GitHub's text renderer handles reST code-blocks very well (or at all).

**Comment by jungshadow** [comment]
Soooooo...LGTY? :)

**Comment by jdmgoogle** [comment]
Yes, LGTM. :)

**Pull request merged**
