### PR TITLE
Address issue #248: expose single-page version of XML docs

### PR DESCRIPTION
**Pull request by cjerdonek**
Okay, I think this is good enough to merge now.  In particular, there are now fewer Sphinx warnings than there were before.  (There were lots of Sphinx warnings affecting the CSV files before I started the previous PR.)

I'm hoping this can be merged again before the "Id" / "Ids" change, because there was a fair amount to do here.  The bulk of the work, aside from updating the Python, was to replace `:doc:` references with `:ref:` references, which are preferred and more flexible for inter-document linking.  This had to be done semi-manually which would be a pain to do again.

There is one issue that can be taken care of in a subsequent commit, namely making all hyperlink "refs" choose the appropriate single-page vs. multi-page ref, depending on which version the link resides in.  That can be done dynamically / automatically by the Python when it is generating the single vs. multi-page files.

### CODE REVIEW

**Comment by cjerdonek** [comment]
There are other improvements in this PR, too, like putting all of the auto-generated reST files in a separate `docs/built_rst` directory.  This way the auto-generated files can be kept separate and not intermingled with the reST files that need to manually edited.  It makes things clearer that way, too.

**Comment by cjerdonek** [comment]
>There is one issue that can be taken care of in a subsequent commit, namely making all hyperlink "refs" choose the appropriate single-page vs. multi-page ref,

Okay, this is now done, too.  And I've also brought the number of Sphinx warnings down to zero.

**Comment by jdmgoogle** [comment]
LGTM

Ping @pstenbjorn

**Comment by jdmgoogle** [comment]
Also I'm fine merging these documentation changes into #299 as we go so you won't have to changes your PRs.

**Comment by pstenbjorn** [comment]
@cjerdonek and @jdmgoogle this LGTM.  Thank you @cjerdonek!

**Comment by cjerdonek** [comment]
Thanks a lot, @jdmgoogle and @pstenbjorn.

**Pull request merged**
