### PR TITLE
Fix vip5 spec so it validates.

### PR DESCRIPTION
**Pull request by jdmgoogle**
Move some xs:all elements to xs:sequence since we can't have maxOccurs=unbounded in an xs:all element.

### CODE REVIEW

**Comment by cjerdonek** [comment]
LGTM (does it help for me to say this anymore?)

**Comment by jdmgoogle** [comment]
@cjerdonek Yes. It's a positive signal to other reviewers. I or @jungshadow or @pstenbjorn might look at your LGTM and think "okay, I trust him" and give the 'formal' LGTM with much less effort.

**Comment by jdmgoogle** [comment]
Pinging @jungshadow @pstenbjorn and @jen-tolentino for Pew approval.

**Comment by pstenbjorn** [comment]
@jdmgoogle LGTM

**Pull request merged**
