### PR TITLE
Address Issue #85 -  Fixed case isssues in XSD

### PR DESCRIPTION
**Pull request by demcg**
Changed the casing of elements, attributes, and enumerations to match the style guide listed in #85

### CODE REVIEW

**Comment by jungshadow** [comment]
Beautiful.

**Comment by demcg** [comment]
@jungshadow  should I wait for @cjerdonek or merge now?

**Comment by jungshadow** [comment]
@jdmgoogle @pstenbjorn Can either of you bless this to get one more set of eyes before merging?

**Comment by pstenbjorn** [comment]
@demcg and @jungshadow the only issues I see are two inconsistently cased element names as below:
```<xs:element name="electionsUrl" type="xs:string" minOccurs="0" />```
```<xs:element name="registrationUrl" type="xs:string" minOccurs="0" />```
Think these should be named `ElectionsUrl` and `RegistrationUrl`.

**Comment by demcg** [comment]
@pstenbjorn nice catch, thanks

**Pull request merged**
