### PR TITLE
Update HISTORY.md with changes since 3.x

### PR DESCRIPTION
**Pull request by jdmgoogle**
Updated the HISTORY.md document to highlight most of the changes we've made since the 3.x release. Changes are broken down into how they update the spec itself and how they update the process of contributing to and designing the spec.

### CODE REVIEW

**Comment by jdmgoogle** [comment]
This is to address #40 and #98.

**Comment by jungshadow** [comment]
Beautiful.

**Comment by jungshadow** [comment]
Or "LGTM" to be explicit.

**Comment by jungshadow** [comment]
@cjerdonek @pstenbjorn What do y'all think about this?

**Comment by jdmgoogle** [comment]
Ping @jktomer @pstenbjorn @cjerdonek

**Comment by pstenbjorn** [comment]
LGTM and I agree with @jungshadow

**Comment by jdmgoogle** [comment]
Thank you. Merging.

**Pull request merged**
