### PR TITLE
Updates HISTORY.md to add version 6.0 changes

### PR DESCRIPTION
**Pull request by jswiesner**

### CODE REVIEW

**Comment by jswiesner** [comment]
@afsmythe I'm unable to edit the PR to add reviewers. Can you give me access to be able to do that? I'll send PRs like this your way as I start working through v6 doc updates.

**Comment by afsmythe** [comment]
@jswiesner can you try now?

**Comment by jswiesner** [comment]
@afsmythe still doesn't work. I can only edit the title of this PR and close it out.

**Comment by afsmythe** [comment]
@jswiesner You're set for Write access. Should that be enough? It says your account has a "Pending invitation". 

Do you think you'll need to acknowledge the invitation?

https://github.com/votinginfoproject/vip-specification/invitations

**Comment by jswiesner** [comment]
Ah yep, I hadn't seen the email yet that I need to accept. Sorry about that! All set now.

**Review by afsmythe — APPROVED** [review]
Looks good! Thanks for putting this together.

**Pull request merged**
