### PR TITLE
Documentation for RetentionContest

### LINKED ISSUE #204: Document RetentionContest element
Document the `RetentionContest` element.

### PR DESCRIPTION
**Pull request by jungshadow**
Currently missing an example from the sample feed, but, when complete, this closes #204

### CODE REVIEW

**Comment by jungshadow** [comment]
As I mentioned in #206, I propose we accept this and add the example when we have data for the sample feed. Cool?

**Comment by jdmgoogle** [comment]
LGTM

**Comment by jungshadow** [comment]
Thanks! /cc @pstenbjorn @cjerdonek @pkoms @nomadaisy

**Comment by pstenbjorn** [comment]
LGTM

**Pull request merged**
