### PR TITLE
Address Issue #87 - changed Urls of type xs:string to type xs:anyURI

### PR DESCRIPTION
**Pull request by demcg**
Changed xs:string to xs:anyURI to address #87

### CODE REVIEW

**Comment by cjerdonek** [comment]
LGTM

**Comment by pstenbjorn** [comment]
Looks good.  Can you please let me know when this is merged and I will pull vip5 and work on precinct split mods.

**Comment by cjerdonek** [comment]
@pstenbjorn I will wait for you to merge precinct split before working on #77.

**Comment by demcg** [comment]
@pstenbjorn @cjerdonek Address Issue #87 - changed Urls of type xs:string to type xs:anyURI - merged

**Pull request merged**
