### PR TITLE
Fix for Read the Docs online documentation

### LINKED ISSUE #252: Fix documentation on Read the Docs
In my last PR #250, I unwittingly introduced a bug that completely borked the online documentation and removed the theme stylesheet. I'll create a PR to fix that.

### PR DESCRIPTION
**Pull request by jungshadow**
This should fix #252.

### CODE REVIEW

**Comment by jungshadow** [comment]
Hoping to get this one merged in quickly. Can y'all take a look? @jdmgoogle @jktomer @pstenbjorn @cjerdonek

**Comment by cjerdonek** [comment]
Okay to me.

**Comment by jdmgoogle** [comment]
LGTMIS (I suppose) :)

**Comment by jungshadow** [comment]
@jdmgoogle @cjerdonek Thanks, guys. Yeah...lets hope it works this time. Both worked locally so... [shrugs]

**Pull request merged**
