### PR TITLE
Merge gh-pages into master

### PR DESCRIPTION
**Pull request by jdmgoogle**
I'm trying to merge vip5 back into master, so this is going to be PR 1 of **N** (hopefully **N** will be small).

I apologize in advance if this turns into a big commit/revert storm.

### CODE REVIEW

**Comment by cjerdonek** [comment]
> I'm trying to merge vip5 back into master

Wouldn't this be at most two commits: 1) merge master to vip5 (which may be a no-op), and then 2) merge vip5 to master (which will essentially be a copy)?

**Comment by jdmgoogle** [comment]
@cjerdonek Possibly. I know just enough git to be dangerous but possibly not productive. If you take a quick stab at this I can review the PRs.

**Comment by cjerdonek** [comment]
@jdmgoogle I missed this message. If you still want me to do this, let me know. I see you also asked @jungshadow on the other issue. I know what needs to be done and can include the git commands for future reference if I do the PR.

**Comment by jungshadow** [comment]
@cjerdonek All you :)

**Comment by cjerdonek** [comment]
@jungshadow @jdmgoogle Okay, I made the PR here: #296.

**Pull request closed without merging**
