### PR TITLE
Documentation for Person

### LINKED ISSUE #203: Finish documenting Person element
Finish documenting the `Person` element. There are only a few fields left.

### PR DESCRIPTION
**Pull request by jungshadow**
Closes #203

### CODE REVIEW

**Comment by jdmgoogle** [comment]
LGTM. Please add

1. a note that `Title` and `Profession` are `InternationalizedText` because these are elements which are displayed on ballots in different languages; and
2. a sample block from the sample feed.

Thanks.

**Comment by pstenbjorn** [comment]
Pending @jdmgoogle suggestion, LGTM

**Comment by jungshadow** [comment]
@jdmgoogle @pstenbjorn Thanks for looking at this.

> ...a note that Title and Profession are InternationalizedText because these are elements which are displayed on ballots in different languages...

Done.

> ...a sample block from the sample feed.

[The sample I have on `Person`](https://github.com/votinginfoproject/vip-specification/pull/212/files#diff-067a7f14703106463c62a22bf1a29a2fL67) was lifted from the sample feed. Is there an issue with it?

**Comment by jdmgoogle** [comment]
> The sample I have on Person was lifted from the sample feed. Is there an issue with it?

Weird, the sample didn't show up when I did [This PR] ~> Files Changed ~> View.

**Comment by jungshadow** [comment]
Going to assume I have two LGTMs here :) Merging.

**Pull request merged**
