### PR TITLE
Updated sample feed to provide an example of a "Top-Two" primary.

### PR DESCRIPTION
**Pull request by jdmgoogle**
This addresses issue #268.

Also removed all EndorsingPartyIds fields since we're changing how those work.

Pinging @cjerdonek @pstenbjorn @Josh-LACRRCC and @kennethmbennett  for review and feedback.

### CODE REVIEW

**Comment by cjerdonek** [comment]
Thanks, @jdmgoogle. It seems like the docs should also be updated in appropriate spots, for example saying in the "Party" docs that a Party object can also be used a "dummy" party to indicate a type of primary and also to indicate the lack of a party preference (in particular, Party objects are not just in correspondence with political parties).  And perhaps also clarifying what the various "PartyId" attributes mean.

**Comment by jdmgoogle** [comment]
@cjerdonek Done.

**Comment by cjerdonek** [comment]
:+1:

**Comment by jdmgoogle** [comment]
Ping @pstenbjorn

**Comment by pstenbjorn** [comment]
@jdmgoogle looks good.

**Pull request merged**
