### PR TITLE
Update enumerations to match 1622.2

### PR DESCRIPTION
**Pull request by jdmgoogle**
Changes include:
- Breaking up 'council' into 'city-council' and 'county-council';
- Moving 'write-in' status from `CandidatePostElectionStatus' to `CandidatePreElectionStatus`;
- Adding `DistrictType` 'village'; and
- Adding a hyphen to the middle of 'statehouse' and 'statesenate'.

### CODE REVIEW

**Comment by jungshadow** [comment]
LGTM.

**Comment by pstenbjorn** [comment]
@jdmgoogle can we leave the generic `council` as well as these enums?  There are jurisdictions that are neither cities nor counties that have a council (e.g. D.C. and towns in Virginia).

**Comment by jungshadow** [comment]
@pstenbjorn To play devil's advocate, couldn't they be classified as 'city-council' (NB: I know that it's a harder sell for "town")?

**Comment by pstenbjorn** [comment]
@jungshadow they could.  And for our use case perhaps I should just say, LGTM, since, perhaps I am just being persnickety.

**Comment by jdmgoogle** [comment]
Okay. Merging.

**Pull request merged**
