### PR TITLE
Address issue #230: synch with latest 1622.2

### PR DESCRIPTION
**Pull request by cjerdonek**
This PR is to address issue #230: synch with latest 1622.2.

The initial commit handles VoteVariation.  There may be other things that need updating on the VIP side, but I haven't yet checked exhaustively.

### CODE REVIEW

**Comment by jdmgoogle** [comment]
Thanks for keeping an eye on this.

There are a few other small changes, including

1. the renaming of `OrderedContest.BallotSelectionId` to `OrderedContest.OrderedBallotSelectionId`;
2. Adding `FullName` to `Person`;
3. Adding "town" to `DistrictType`; and
4. Adding "measure" to `VoteVariationType`.

There's also an `OfficeGroup` element, which appears to create a hierarchy of `Office` elements in the same way that 1622.2's `GPUnit` allows for hierarchy. I'm not sure we want to/need to copy that over, though.

I'll take care of items 1-3 in another pull request, and check with @johnpwack about the motivation behind item 4. I'll also file a discussion issue for the `OfficeGroup` element, but I'm hesitant to add something this late in the game.

**Comment by jdmgoogle** [comment]
As for this PR: LGTM.

**Comment by jungshadow** [comment]
LGTM

@jdmgoogle I'll wait until you create another issue to talk about the 1622 updates, but, in short, I think I agree with your thoughts on the `OfficeGroup` structure.

**Comment by cjerdonek** [comment]
Thanks.

**Pull request merged**
