### PR TITLE
BallotMeasureContest doc fixes

### LINKED ISSUE #158: Fix remaining todos on ballot_measure_contest.rst
Two things here for discussion:

* Should `BallotMeasureContest.Type` be required?
* Is `BallotMeasureContest.FullText` a required field?

To the latter bullet point, there were a number of places in the generated doc files where some of the required fields were optional. In [the 3.0 docs](http://votinginfoproject.github.io/vip-specification/#referendumitems), `referendum.title` and `referendum.text` were both required fields. While the similar elements from 3.0 and 5.0 aren't exactly carbon copies, just wanted to make sure it was deliberate. /cc @cjerdonek @jdmgoogle @pstenbjorn

### PR DESCRIPTION
**Pull request by jungshadow**
Fixes #158

### CODE REVIEW

**Comment by jdmgoogle** [comment]
Looks good. Please add some text for `PassageThreshold` to mention that this is where explanations about competing initiative procedures go:

http://ballotpedia.org/Laws_governing_the_initiative_process_in_California#Competing_initiatives

**Comment by jungshadow** [comment]
@jdmgoogle Updated `BallotMeasureContest.PassageThreshold` language. Let me know if it works for you (NB: we can close #158 for now and re-open if necessary).

Ping @pstenbjorn, @jktomer, et al...

**Comment by jdmgoogle** [comment]
LGTM

**Comment by pstenbjorn** [comment]
LGTM

**Pull request merged**
