### PR TITLE
Improve sample validation commands

### PR DESCRIPTION
**Pull request by jdmgoogle**
Update the CONTRIBUTING documentation with a better invocation of xmllint and an invocation of jing.

This addresses #240.

### CODE REVIEW

**Comment by jungshadow** [comment]
LGTM

**Comment by jen-tolentino** [comment]
Ditto!

**Comment by jdmgoogle** [comment]
Thanks!

**Comment by cjerdonek** [comment]
@jen-tolentino beat me to it.  This looked good.  Thanks!

**Pull request merged**
