### PR TITLE
Address issue #241: change FileDate from xs:dateTime to xs:date.

### PR DESCRIPTION
**Pull request by cjerdonek**
Address issue #241: change FileDate from xs:dateTime to xs:date.

### CODE REVIEW

**Comment by jdmgoogle** [comment]
Please update docs/xml/elements/candidate.rst to reflect this change.

**Comment by cjerdonek** [comment]
Updated.

**Comment by jdmgoogle** [comment]
LGTM

**Comment by cjerdonek** [comment]
Thanks. And @jungshadow @jen-tolentino @pstenbjorn, is one of you okay with this?

**Comment by pstenbjorn** [comment]
Okay with it.

**Pull request merged**
