### PR TITLE
Create initial doc structure

### PR DESCRIPTION
**Pull request by jungshadow**
Adding initial doc tree and included generated files for ease of publishing. No real content, yet. Had to add a line to .gitattributes to deal with Windows line endings in `make.bat`. Semi-related to #60.

### CODE REVIEW

**Comment by jungshadow** [comment]
I wouldn't spend too much time looking this over. It's just the structure and some generated files.

**Comment by jdmgoogle** [comment]
Oh, let me just peek at some of the CSS/JS ...



LGTM

**Comment by jen-tolentino** [comment]
LGTM!

**Comment by jungshadow** [comment]
@jdmgoogle :100:

**Comment by cjerdonek** [comment]
FYI, I've used Read the Docs before.  I don't think you're supposed to check in the build folder (i.e. `docs/_build`), only the source files.

**Comment by jungshadow** [comment]
@cjerdonek Wouldn't normally be my preference, either. Since we're unable to use RtD for now, we may just want to just copy the generated files to gh-pages (also not my preference). Having the generated files in the repos will make that process easier for more folks, rather than have to set up sphinx and run the build. We'll kill them off once we're cleared (assuming that happens).

**Comment by cjerdonek** [comment]
Yes, committing the build files to gh-pages would be much better so as not to clutter the history, etc, if that's what you're suggesting.

**Comment by cjerdonek** [comment]
In the past, one workflow I have used is to have two copies of a repo on my machine in sibling folders: one permanently set to the gh-pages branch, and one set to a normal branch.  Then, when working in the normal repo, you can easily set sphinx to output to the build folder in the other repo, e.g. `../vip-gh-pages/docs/_build` or whatever.

**Pull request merged**
