### PR TITLE
Updates the main documentation index to include a list of VIP publishers

### PR DESCRIPTION
**Pull request by jswiesner**
Addresses #297.

### CODE REVIEW

**Comment by jswiesner** [comment]
The GitHub rich diff doesn't seem to have full support for rst syntax (i.e. `:ref:`). Any recommendations on how to verify the formatting for these kinds of changes?

**Comment by afsmythe** [comment]
Have always built the documentation and viewed locally with a web server. Similar to: https://github.com/votinginfoproject/vip-specification/blob/vip52/CONTRIBUTING.md#building-the-documentation 

Can you elaborate on what you're thinking of highlighting a part from what is [present here](https://github.com/votinginfoproject/vip-specification/pull/417/files)?

**Comment by jswiesner** [comment]
Thanks, I hadn't seen that guide about building the documentation!

Absent of input from others, I don't have any other ideas for things to add under #297. Any thoughts on more useful information we could include here?

**Review by afsmythe — APPROVED** [review]
I think this is a good start for the section. If open source data management projects or additional publishers are made available they can be listed here.

**Pull request merged**
