### PR TITLE
Added an IncludesAllStreets to support city wildcarding.

### PR DESCRIPTION
**Pull request by jdmgoogle**
This should address #289.

### CODE REVIEW

**Comment by jungshadow** [comment]
I could see an argument both ways on this, but, if `IncludesAllStreets` is "true", could the inclusion of `OddEvenBoth` potentially be error-prone? It's useful for `IncludesAllAddresses`, but I can see how it might cause problems in this case. If y'all have already discussed this and sorted it out, LGTM.

**Comment by jdmgoogle** [comment]
Ping to @pstenbjorn @nomadaisy @MariaBianchi @cjerdonek.

**Comment by pstenbjorn** [comment]
@jdmgoogle this looks good to me as far as documentation is concerned.  I am curious how this might be represented in a csv load.

**Comment by jdmgoogle** [comment]
@pstenbjorn You're curious as in "I would like you, @jdmgoogle, to explain your thoughts" or "I would like @nomadaisy to weigh in"?

**Comment by pstenbjorn** [comment]
@jdmgoogle as in, I am sure @nomadaisy has factored this in the csv, just interested in the mechanics.

**Comment by jdmgoogle** [comment]
Ping @nomadaisy

**Comment by jdmgoogle** [comment]
Ping @MariaBianchi

**Comment by MariaBianchi** [comment]
@jdmgoogle We'll take a look at this, and though I don't have an answer at this moment, I'll try to have one by next week.  This is one of several areas where I think the CSVs need another look.

**Comment by jdmgoogle** [comment]
Friendly ping to @MariaBianchi and @nomadaisy

**Comment by nomadaisy** [comment]
I did include it as a boolean field in the street_segment.txt CSV structure documentation and example, so we are good to go. I envision the other address fields being blank if this is **true**, and the processor should ignore any populated address fields if this field is **true**.

**Comment by jdmgoogle** [comment]
@nomadaisy Good suggestion. I updated the documentation to make `OddEvenBoth` optional. PTAL, along with @pstenbjorn and @cjerdonek

**Comment by pstenbjorn** [comment]
@jdmgoogle if that is the case, the following change might also be needed:

`<xs:element name="OddEvenBoth" type="OebEnum"  minOccurs="0"/>`

**Comment by jdmgoogle** [comment]
@pstenbjorn Good catch. Updated.

**Comment by nomadaisy** [comment]
LGTM

**Comment by jdmgoogle** [comment]
I'm going to optimistically assume that @pstenbjorn is okay with this. If he isn't, then all of you are witnesses that I'm okay with him yelling at me at the next VIP conference. :)

**Comment by pstenbjorn** [comment]
Yes, so no yelling required.

**Pull request merged**
