### PR TITLE
Feature/precinct splits

### PR DESCRIPTION
**Pull request by pstenbjorn**
PR for the suggested simplification of precinct/split management.  Modified the single element for `precinct` to act in all places where `precinct_id` and `precinct_split_id` are related and used.  Specifically affects `electoral_district`, `street_segment`, and `polling_location`.

This addresses issue [https://github.com/votinginfoproject/vip-specification/issues/27]

### CODE REVIEW

**Comment by jungshadow** [comment]
@pstenbjorn Did you mean to merge this into vip5?

**Comment by pstenbjorn** [comment]
@jungshadow yes not into master.

**Comment by jdmgoogle** [comment]
I'm still coming back up to speed from vacation, so this may be a stupid question (so I apologize in advance). I thought we were getting rid of the precinct_split object, using only precinct objects, and adding a split_name field to the precinct object. The current vip5 branch seems to still have both precinct and precinct_split objects.

**Comment by pstenbjorn** [comment]
@jdmgoogle not sure why the changes did not get propagated.  I will check out vip5 again and create a branch and a pull request to get these in.

**Comment by demcg** [comment]
@pstenbjorn If you get any merge conflicts related to the attribute reorder, I can help with the resolution.

**Comment by jungshadow** [comment]
@pstenbjorn @jdmgoogle That might be my bad as I tried to fix some merge issues and may have excluded some changes. That said, let's wait until @demcg's gives us a clean, style-guide-following vip5 branch to work from and then create a new pull request from that. Cool?

**Pull request closed without merging**
