### PR TITLE
Document InternationalizedText and LanguageString

### LINKED ISSUE #198: Document InternationalizedText and LanguageString
Document the `InternationalizedText` and `LanguageString` elements.

### PR DESCRIPTION
**Pull request by jungshadow**
Closes #198.

### CODE REVIEW

**Comment by jdmgoogle** [comment]
Thanks. Two comments/ideas:

1. Dump the `LanguageString` documentation in with `InternationalizedText` since it's really just one cohesive whole.
2. Add in some sample XML.

Otherwise it looks good.

**Comment by jungshadow** [comment]
@jdmgoogle Thanks!

> Dump the LanguageString documentation in with InternationalizedText since it's really just one cohesive whole.

Very much agree and done.

> Add in some sample XML.

Since `InternationalizedText` is used as a type, it seems more appropriate to expand the examples in the elements that use `InternationalizedText`. While this is clearly harder (mostly because we don't have real data for translations), I feel we can call it a "Work in Progress" for now and open up separate issues to expand said elements, which are now listed in the `InternationalizedText` docs. I'm hoping @Josh-LACRRCC or @kennethmbennett might be able to help with some of these examples.

**Comment by jdmgoogle** [comment]
LGTM

**Comment by jungshadow** [comment]
Thanks! /cc @pstenbjorn @pkoms @cjerdonek @nomadaisy

**Comment by cjerdonek** [comment]
FYI, if you want some examples, you can look here: https://github.com/cjerdonek/sf-base-election-data/tree/master/pre_data/i18n/phrases_csv

This directory contains some information culled from the SF Department of Elections, with official translations of some election phrases into Spanish and Chinese (and some Filipino).

**Comment by pstenbjorn** [comment]
LGTM

**Comment by jungshadow** [comment]
I'll definitely take a look through it, @cjerdonek. Thanks!

**Pull request merged**
