### PR TITLE
Fixed PollingLocation documentation issues

### LINKED ISSUE #220: Fix PollingLocation Documentation Issues
Reconcile these two cells in https://github.com/votinginfoproject/vip-specification/blob/vip5/docs/xml/elements/polling_location.rst

Required? | Error Handling?
-------------- | -------------
Optional | If the field is invalid or not present, the implementation is required to ignore the PollingLocation element that contains it.

### PR DESCRIPTION
**Pull request by jungshadow**
Closes #220

### CODE REVIEW

**Comment by jungshadow** [comment]
@pkoms Can you take a look at the fixes and let me know if this jives with what you were thinking?

**Comment by jungshadow** [comment]
Mental note: need to remember to update `HISTORY.md`. Will do in next push.

**Comment by jungshadow** [comment]
OK...in light of @pkoms...[doing something else](http://bukk.it/cumberdrink.gif), anyone else want to weigh in here? :)

**Comment by jdmgoogle** [comment]
LGTM. And what, exactly, is @pkoms off doing?

**Comment by nomadaisy** [comment]
I believe what @pkoms was talking about was the AddressLine being "Optional." Is that accurate? In the previous version of the spec, it is Required. The current documentation shows as Optional: http://vip-specification.readthedocs.org/en/vip5/xml/elements/polling_location.html

**Comment by jungshadow** [comment]
@jdmgoogle Unclear, but [here's the best representation I can come up with](http://bukk.it/howidobasicallyeverything.gif).

**Pull request merged**
