### PR TITLE
Sync the VIP spec with v50 of the NIST standard

### PR DESCRIPTION
**Pull request by jdmgoogle**
This addresses and should close out issue #305.

### CODE REVIEW

**Comment by cjerdonek** [comment]
:+1:

**Comment by jdmgoogle** [comment]
Ping @pstenbjorn

**Comment by jdmgoogle** [comment]
Ping to new Pew member @rhoffmanpew to review this pull request.

(And welcome!0

**Comment by pstenbjorn** [comment]
@jdmgoogle LGTM

**Pull request merged**
