### PR TITLE
Un-Venetian-Blind ContactInformation

### PR DESCRIPTION
**Pull request by jdmgoogle**
It makes more sense to have the content included with the elements instead of mentioned by reference.

### CODE REVIEW

**Comment by cjerdonek** [comment]
This isn't actually "un-Venetian-Blinding" it since the type definition is at the top level.

My only suggestion is to change the "id" attribute on the ContactInformation object to the following, as we discussed previously:

    <xs:attribute name="identifier" type="xs:string" />

This is because the ID is no longer a required ID, but can be present to link the data to a flat file, if a flat file was used.  This is the same pattern that InternationalizedText uses.

**Comment by cjerdonek** [comment]
After that, LGTM.

**Comment by pstenbjorn** [comment]
@jdmgoogle I agree with @cjerdonek assessment but my question is what is the value of including an identifier if these elements are not referenced by ID?

**Comment by cjerdonek** [comment]
If the objects are provided as flat files, providing an identifier lets you link to the data back to the row of the flat file it came from.  Otherwise, there is no definitive way to link it back.

**Comment by jdmgoogle** [comment]
Good idea. Done.

**Comment by jdmgoogle** [comment]
Whoops. Good catch (even though xs:ID is just a subset of xs:string).

**Comment by cjerdonek** [comment]
Thanks, LGTM.

**Comment by jdmgoogle** [comment]
Based on the comments from @cjerdonek and @pstenbjorn I'm assuming this meeting PR review guidelines. Merging.

**Pull request merged**
