### PR TITLE
Address issue #237: alphabetize elements inside VipObject type.

### PR DESCRIPTION
**Pull request by cjerdonek**
Address issue #237: alphabetize elements inside VipObject type.

### CODE REVIEW

**Comment by jdmgoogle** [comment]
LGTM

**Comment by cjerdonek** [comment]
Ping @jungshadow @jen-tolentino @pstenbjorn, does this okay?

**Comment by jdmgoogle** [comment]
Ping @jungshadow @jen-tolentino @pstenbjorn.

**Comment by jungshadow** [comment]
LGTM

**Comment by cjerdonek** [comment]
Thanks, guys.

**Pull request merged**
