### PR TITLE
Merge documentation from master

### PR DESCRIPTION
**Pull request by jungshadow**
This deals with issues in #48 (i.e. editing the docs directly in this branch should be fine).

### CODE REVIEW

**Comment by jungshadow** [comment]
@pstenbjorn @cjerdonek @jdmgoogle Once more...with feeling :)

**Comment by cjerdonek** [comment]
@jungshadow To understand this PR, you are just merging the document files from current master into a feature branch off vip5?  Or are you merging all of master?  And were those all the commits, or was there something more?

**Comment by jungshadow** [comment]
@cjerdonek Just merging in the recent changes from master. We made a lot of changes to the docs to add the CSV formats in.

**Comment by cjerdonek** [comment]
@jungshadow LGTM

**Comment by jungshadow** [comment]
@cjerdonek Excellent! Thanks!

**Pull request merged**
