### PR TITLE
Added Link to Changelog in Documentation

### LINKED ISSUE #40: Changelog missing from web documentation
The web documentation has a link to a "Changelog" in the left column under "Revision History," but there is no Changelog section.

### PR DESCRIPTION
**Pull request by jungshadow**
Closes #40

### CODE REVIEW

**Comment by jungshadow** [comment]
Once we merge into master, this link will have to change, but it's currently fixed in dev. @cjerdonek, can you verify this looks good to you? /cc @pstenbjorn, @jdmgoogle, et al for additional approval

**Comment by pstenbjorn** [comment]
For what its worth, LGTM

**Comment by jdmgoogle** [comment]
FWIW LGTM

**Comment by cjerdonek** [comment]
Great, thanks!

**Comment by cjerdonek** [comment]
:+1:

**Pull request merged**
