### PR TITLE
Address issue #76: document Venetian Blind in style guide

### PR DESCRIPTION
**Pull request by cjerdonek**
This addresses issue #76.

### CODE REVIEW

**Comment by cjerdonek** [comment]
Here is a link to how the PR looks in rendered form: [Style Guide](https://github.com/votinginfoproject/vip-specification/blob/feature/issue-76-style-venetian-blind/docs/style_guide.md#type-definitions-global-vs-local).

**Comment by jdmgoogle** [comment]
Looks Good To Me

**Comment by pstenbjorn** [comment]
@cjerdonek this looks good to me for Venetian Blind guidelines.

**Comment by cjerdonek** [comment]
Great, guys, thanks.  Will merge now.

**Pull request merged**
