### PR TITLE
Documentation for OrderedContest

### LINKED ISSUE #200: Document OrderedContest
Document the `OrderedContest` element.

### PR DESCRIPTION
**Pull request by jungshadow**
Closes #200

### CODE REVIEW

**Comment by jdmgoogle** [comment]
Please put a note indicating that if no `BallotSelectionId` elements are present, the presumed order of selections will be the order of `BallotSelection` items referenced by the underlying `*Contest` element. Also, please add an example from the sample feed.

**Comment by jungshadow** [comment]
> Please put a note indicating that if no BallotSelectionId elements are present, the presumed order of selections will be the order of BallotSelection items referenced by the underlying *Contest element.

Done.

> Also, please add an example from the sample feed.

Had one in there, but made me think to update it as the one I initially chose didn't have `BallotSelectionId` elements.

Related note: I think I understand what you're seeing in regards to the sample XML. Since the samples existed before the rest of the documentation was written in, the diff page truncates the output. On the sidebar, you should see an accordion-looking icon that should expand the diff beyond viewing only what's changed.

**Comment by jdmgoogle** [comment]
Just so we don't leave this dangling ...

> Related note: I think I understand what you're seeing in regards to the sample XML. Since the samples existed before the rest of the documentation was written in, the diff page truncates the output. On the sidebar, you should see an accordion-looking icon that should expand the diff beyond viewing only what's changed.

As you said [here](https://github.com/votinginfoproject/vip-specification/pull/209#issuecomment-108055965) it looks like the PR UI doesn't handle code blocks.

**Comment by jungshadow** [comment]
I'm going to take this as a LGTM :) @pstenbjorn or @cjerdonek or [other]?

**Comment by pstenbjorn** [comment]
Not withstanding display issues: LGTM

**Comment by jdmgoogle** [comment]
To be explicit: LGTM. :)

**Pull request merged**
