### PR TITLE
Add an ExternalIdentifiers element to a Person.

### PR DESCRIPTION
**Pull request by jdmgoogle**
This addresses #340.

Paging @indymag @rsimoes @pstenbjorn @MariaBianchi @nomadaisy etc for review.

### CODE REVIEW

**Comment by indymag** [comment]
Mostly LGTM. 

Non-blocking: there are some diffs (whitespace, maybe?) that I didn't expect in the person.rst

**Comment by jdmgoogle** [comment]
@indymag Yes, it's all whitespace because ExternalIdentifers is wide enough that the RST files had to be re-spaced. That's basically the reason that @cjerdonek wrote the code to generate the RST: because whitespace-sensitive documentation table formats suck.

**Comment by pstenbjorn** [comment]
LGTM

**Comment by indymag** [comment]
LGTM.  Thanks for the explanation.

**Pull request merged**
