### PR TITLE
Documentation for the PartyContest and PartySelection elements.

### PR DESCRIPTION
**Pull request by jdmgoogle**
This addresses issue #202.

### CODE REVIEW

**Comment by jungshadow** [comment]
The descriptions look good. In thinking about the examples, we don't have any for these elements, right?

**Comment by jdmgoogle** [comment]
I don't believe so, no.

**Comment by pstenbjorn** [comment]
@jungshadow I did not create these elements with my sample either.

**Comment by jungshadow** [comment]
I'm game with calling this and #213 good, due to lack of sample data. What say you?

**Comment by jungshadow** [comment]
I'm gonna throw my "LGTM" out there now. /cc @pstenbjorn @cjerdonek @pkoms @nomadaisy

**Comment by pstenbjorn** [comment]
LGTM too

**Comment by jdmgoogle** [comment]
Thanks. Merging.

**Pull request merged**
